baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
googleAnalytics = "G-3T7DYCWC0W"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Lanfran02 - Blog"
    subtitle = "Where write-ups are made."
    keywords = "CTF, Writeup, Hacking"
    copyright = "Lanfran02"
    menuMore = "Write Ups"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Lanfran02"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "THM"
        name = "THM"
        url = "/tags/tryhackme/"
      [[languages.en.menu.main]]
        identifier = "HTB"
        name = "HTB"
        url = "/tags/hackthebox/"
      [[languages.en.menu.main]]
        identifier = "Español"
        name = "Español"
        url = "/es/"
  [languages.es]
    title = "Lanfran02 - Blog"
    subtitle = "Hackeando tu forma de aprender."
    keywords = "CTF, Writeup, Hacking"
    copyright = "Lanfran02"
    menuMore = "Write Ups"
    writtenBy = "Escrito por"
    readMore = "Continuar leyendo"
    readOtherPosts = "Leer otros posts"
    newerPosts = "Posts recientes"
    olderPosts = "Posts antiguos"
    minuteReadingTime = "mins lectura"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.es.params.logo]
      logoText = "Lanfran02"
      logoHomeLink = "/es/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "about"
        name = "Acerca de mí"
        url = "/es/about"
      [[languages.es.menu.main]]
        identifier = "THM"
        name = "THM"
        url = "/es/tags/tryhackme/"
      [[languages.es.menu.main]]
        identifier = "HTB"
        name = "HTB"
        url = "/es/tags/hackthebox/"
      [[languages.es.menu.main]]
        identifier = "English"
        name = "English"
        url = "/"
