name: Latest wrietup post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 18 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest writeups posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in writeups
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 3
          template: '<td><a href="https://lanfran02.github.io/$url/"><img width="140px" src="https://lanfran02.github.io/$url/cover.jpeg"></a></td>$newline<td><a href="https://lanfran02.github.io/$url/">$title</a><br/>$description</td>$newline'
          feed_list: "https://lanfran02.github.io/index.xml"
